/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-10-07 08:12:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.text.*;
import java.util.*;
import java.lang.*;

public final class login_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로그인 폼</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/pabicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/login2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/slick.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/slick-theme.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poor+Story\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	String name = (String)session.getAttribute("name");
	if(name == null) {

      out.write("\r\n");
      out.write("<!--header start//-->\r\n");
      out.write("<header id=\"dowowow\">\r\n");
      out.write("	<a href=\"#dowowow\" class=\"ssg\"><div id=\"top\"></div></a>\r\n");
      out.write("	<div id=\"header_top\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"#\"></a></li>\r\n");
      out.write("			<li><a href=\"#\"></a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"logo\">\r\n");
      out.write("		<a href=\"index.jsp\"><img src=\"images/design_index_03red.jpg\" alt=\"헤드메뉴\" width=\"262\" sizes=\"100%\"></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"header_menu\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<div class=\"header_menu_bar\">\r\n");
      out.write("				<li><a href=\"Good.html\" class=\"bold\">상품</a></li>\r\n");
      out.write("				<li><a href=\"#\">보드게임</a></li>\r\n");
      out.write("				<li><a href=\"board.html\" class=\"bold\">커뮤니티</a></li>\r\n");
      out.write("				<li><a href=\"event.html\" class=\"bold\">이벤트</a></li>\r\n");
      out.write("				<li><a href=\"#\">오프라인 매장</a></li>\r\n");
      out.write("			</div>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--header end//-->\r\n");
      out.write("<div class=\"menu\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"login-wrapper\">\r\n");
      out.write("			<h2>Login</h2>\r\n");
      out.write("			<form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/login_pro.jsp\" id=\"login-form\">\r\n");
      out.write("				<input type=\"text\" name=\"id\" placeholder=\"ID\">\r\n");
      out.write("				<input type=\"password\" name=pw placeholder=\"Password\">\r\n");
      out.write("				<label for=\"remember-check\" class=\"idsave\">\r\n");
      out.write("					<input type=\"checkbox\" id=\"remember-check\">  아이디 저장하기 | 회원가입 \r\n");
      out.write("				</label>\r\n");
      out.write("				<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer_box\">\r\n");
      out.write("		<div class=\"footer_title\">			\r\n");
      out.write("			<span id=\"susu\">소소\r\n");
      out.write("				<span class=\"footer_title_wja\"></span>\r\n");
      out.write("				<span class=\"footer_title_wja2\"></span>\r\n");
      out.write("			</span>\r\n");
      out.write("			보드게임\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_txt\">\r\n");
      out.write("			회사소개ㅣ개인정보취급방침ㅣ이용약관ㅣ광고 & 제휴문의ㅣ사업자정보조회<br>\r\n");
      out.write("			상호명 : 소소보드게임  　대표 : 이세준   본사·전시장 : 서울특별시 강동구 천호동 (신주소 : 산신길 6) <br>\r\n");
      out.write("\r\n");
      out.write("			TEL : 010-5098-3921　  사업자번호 : 134-86-89622  　Email : tmdfl980520@naver.com <br>\r\n");
      out.write("\r\n");
      out.write("			개인정보 취급 담당자 : 이세준  　통신판매업신고번호 : 제2012-서울강동-0442호 <br>\r\n");
      out.write("\r\n");
      out.write("			Copyright ⓒ 2018 Glorygagu. All Rights Reserved. Designed by bizvalley\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	} else {
			
      out.write("\r\n");
      out.write("		<!--header start//-->\r\n");
      out.write("<header id=\"dowowow\">\r\n");
      out.write("	<a href=\"#dowowow\" class=\"ssg\"><div id=\"top\"></div></a>\r\n");
      out.write("	<div id=\"header_top\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"#\">");
      out.print( name );
      out.write("님 로그인 중</a></li>\r\n");
      out.write("			<li><a href=\"");
 request.getContextPath(); 
      out.write(" logout.jsp\">로그아웃</a></a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"logo\">\r\n");
      out.write("		<a href=\"index.jsp\"><img src=\"images/design_index_03red.jpg\" alt=\"헤드메뉴\" width=\"262\" sizes=\"100%\"></a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"header_menu\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<div class=\"header_menu_bar\">\r\n");
      out.write("				<li><a href=\"Good.html\" class=\"bold\">상품</a></li>\r\n");
      out.write("				<li><a href=\"#\">보드게임</a></li>\r\n");
      out.write("				<li><a href=\"board.html\" class=\"bold\">커뮤니티</a></li>\r\n");
      out.write("				<li><a href=\"event.html\" class=\"bold\">이벤트</a></li>\r\n");
      out.write("				<li><a href=\"#\">오프라인 매장</a></li>\r\n");
      out.write("			</div>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--header end//-->\r\n");
      out.write("<div class=\"menu\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"login-wrapper\">\r\n");
      out.write("			<h2>Login</h2>\r\n");
      out.write("			<form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/login_pro.jsp\" id=\"login-form\">\r\n");
      out.write("				<input type=\"text\" name=\"id\" placeholder=\"ID\">\r\n");
      out.write("				<input type=\"password\" name=pw placeholder=\"Password\">\r\n");
      out.write("				<label for=\"remember-check\" class=\"idsave\">\r\n");
      out.write("					<input type=\"checkbox\" id=\"remember-check\">  아이디 저장하기 | 회원가입 \r\n");
      out.write("				</label>\r\n");
      out.write("				<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer_box\">\r\n");
      out.write("		<div class=\"footer_title\">			\r\n");
      out.write("			<span id=\"susu\">소소\r\n");
      out.write("				<span class=\"footer_title_wja\"></span>\r\n");
      out.write("				<span class=\"footer_title_wja2\"></span>\r\n");
      out.write("			</span>\r\n");
      out.write("			보드게임\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer_txt\">\r\n");
      out.write("			회사소개ㅣ개인정보취급방침ㅣ이용약관ㅣ광고 & 제휴문의ㅣ사업자정보조회<br>\r\n");
      out.write("			상호명 : 소소보드게임  　대표 : 이세준   본사·전시장 : 서울특별시 강동구 천호동 (신주소 : 산신길 6) <br>\r\n");
      out.write("\r\n");
      out.write("			TEL : 010-5098-3921　  사업자번호 : 134-86-89622  　Email : tmdfl980520@naver.com <br>\r\n");
      out.write("\r\n");
      out.write("			개인정보 취급 담당자 : 이세준  　통신판매업신고번호 : 제2012-서울강동-0442호 <br>\r\n");
      out.write("\r\n");
      out.write("			Copyright ⓒ 2018 Glorygagu. All Rights Reserved. Designed by bizvalley\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		");
	
	}

      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write(" $(document).ready(function() { \r\n");
      out.write("    $(\"a.ssg\").anchorAnimate() \r\n");
      out.write(" }); \r\n");
      out.write(" jQuery.fn.anchorAnimate = function(settings) { \r\n");
      out.write("    settings = jQuery.extend({ \r\n");
      out.write("    speed : 1000 \r\n");
      out.write("    }, settings);     \r\n");
      out.write("    return this.each(function(){ \r\n");
      out.write("    var caller = this \r\n");
      out.write("    $(caller).click(function (event) {     \r\n");
      out.write("    event.preventDefault() \r\n");
      out.write("    var locationHref = window.location.href \r\n");
      out.write("    var elementClick = $(caller).attr(\"href\") \r\n");
      out.write("    var destination = $(elementClick).offset().top; \r\n");
      out.write("    $(\"html:not(:animated),body:not(:animated)\").animate({ scrollTop: destination}, settings.speed, function()  \r\n");
      out.write("    { \r\n");
      out.write("    window.location.hash = elementClick \r\n");
      out.write("    }); \r\n");
      out.write("     return false; \r\n");
      out.write("    }) \r\n");
      out.write("    }) \r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
